version: '3.9'

networks:
  kafka:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"   # host access
      - "9093:9093"   # internal Docker listener
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # auto-create topics for dev
    depends_on:
      - zookeeper
    networks:
      - kafka

  kafdrop:
    image: obsidiandynamics/kafdrop:3.28.0
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
    networks:
      - kafka

  consumerapi:
    build:
      context: .
      dockerfile: ConsumerApi/Dockerfile
    container_name: consumerapi
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    depends_on:
      - kafka
    ports:
      - "8086:5001"
    networks:
      - kafka

  producerapi:
    build:
      context: .
      dockerfile: ProducerApi/Dockerfile
    container_name: producerapi
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    depends_on:
      - kafka
    ports:
      - "8085:5000"
    networks:
      - kafka
